export const Data = [
    {
         id:1,
         img:"./Images/iphoneX.png",
         screenImg:"./Images/Ecommerce.png",
         title:"E-Commerce",
         desc:"Full E-commerce wesite with mobile friendly design. The website is ready with register/Login extension to keep track of your business.Start your own online business with Flex. Developments by creatng your online store brand. Take your business to the next level and start follow up with the technology. You can Start your online business from as low as 50$ a Month and you can try first with 7 days trial.(NO CREDIT CARD REQUIRED)",
         type:"row",
         classDiv: "phone",
         classimg1:"phoneScreen",
         classimg2:"phoneApp",
     },
     
     {
         id:2,
         img:"./Images/laptop.png",
         screenImg:"./Images/Dashboard.png",
         title:"Admin Dashboard",
         desc:"Any wesbsite needs an admin dashboard. Nice design with Dark Mode toggeling button and graphs that summarize all your buisness data",
         type:"rowReverse",
         classDiv: "laptop",
         classimg1:"laptopScreen",
         classimg2:"laptopApp",
     },
     {
         id:3,
         img:"./Images/iphoneX.png",
         screenImg:"./Images/portfolio.png",
         title:"Portfolio",
         desc:"Creat your own stunning website just like this one. If your are a skilled freelancer be more professional by owning a portfolio wesbite added with a contact form feature connected by backend database.",
         type:"row",
         classDiv: "phone",
         classimg1:"phoneScreen",
         classimg2:"phoneApp",
     },
     {
         id:4,
         img:"./Images/laptop.png",
         screenImg:"./Images/immigration.png",
         title:"Immigration Website",
         desc:"Full immigration provides information with multiple pages provide certified information to visitors to help them immgrate to their dream location",
         type:"rowReverse",
         classDiv: "laptop",
         classimg1:"laptopScreen",
         classimg2:"laptopApp",
     },
 ];